export const audioMap = {
  "Welcome to learn Equivalent Fractions! Around the world.": "/assets/audio/audio_welcome_to_learn_equivalent_fractions_around_the_world_0.mp3",
  "Hmm... are these equal?": "/assets/audio/audio_hmm_are_these_equal_1.mp3",
  "John has 1 by 2 of a pizza. Sarah has 2 by 4 of the SAME size pizza. Who has more?": "/assets/audio/audio_john_has_1_by_2_of_a_pizza_sarah_has_2_by_4_of_the_same_size_pizza_who_has_more_2.mp3",
  "When two fractions cover the same area, they are called equivalent fractions!": "/assets/audio/audio_when_two_fractions_cover_the_same_area_they_are_called_equivalent_fractions_3.mp3",
  "Mei has a chocolate bar cut into 4 pieces and eats 2. John's bar is cut into 2 — he eats 1. Did they eat the same amount?": "/assets/audio/audio_mei_has_a_chocolate_bar_cut_into_4_pieces_and_eats_2_john_s_bar_is_cut_into_2_he_4.mp3",
  "Two fractions that look different can still be equal!": "/assets/audio/audio_two_fractions_that_look_different_can_still_be_equal_5.mp3",
  "Priya's dosa is cut into 6 pieces. She eats 3. Is that the same as eating 1 by 2?": "/assets/audio/audio_priya_s_dosa_is_cut_into_6_pieces_she_eats_3_is_that_the_same_as_eating_1_by_2_6.mp3",
  "3 by 6 and 1 by 2... are they secretly the same fraction?": "/assets/audio/audio_3_by_6_and_1_by_2_are_they_secretly_the_same_fraction_7.mp3",
  "Meet John from Toronto. He has a chocolate bar cut into 2 equal pieces. He eats 1 piece. That's one half!": "/assets/audio/audio_meet_john_from_toronto_he_has_a_chocolate_bar_cut_into_2_equal_pieces_he_eats_1__8.mp3",
  "\"John eats 1 by 2 of his chocolate bar!\"": "/assets/audio/audio_john_eats_1_by_2_of_his_chocolate_bar_9.mp3",
  "One out of two equal parts!": "/assets/audio/audio_one_out_of_two_equal_parts_10.mp3",
  "Meet Mei from Beijing. She has the SAME size chocolate bar, cut into 4 equal pieces. She eats 2 pieces. That's two quarters!": "/assets/audio/audio_meet_mei_from_beijing_she_has_the_same_size_chocolate_bar_cut_into_4_equal_piece_11.mp3",
  "\"Mei eats 2 by 4 of her bar!\"": "/assets/audio/audio_mei_eats_2_by_4_of_her_bar_12.mp3",
  "Two out of four equal parts!": "/assets/audio/audio_two_out_of_four_equal_parts_13.mp3",
  "Look — the shaded part is exactly equal! John's 1 by 2 and Mei's 2 by 4 cover the same area. They are EQUIVALENT fractions!": "/assets/audio/audio_look_the_shaded_part_is_exactly_equal_john_s_1_by_2_and_mei_s_2_by_4_cover_the_s_14.mp3",
  "\"1 by 2 equals 2 by 4 — same value, different names!\"": "/assets/audio/audio_1_by_2_equals_2_by_4_same_value_different_names_15.mp3",
  "Equivalent means equal value!": "/assets/audio/audio_equivalent_means_equal_value_16.mp3",
  "Meet Priya from Mumbai. Her dosa is cut into 6 equal pieces. She eats 3 pieces — that's 3 by 6. Is it the same as 1 by 2?": "/assets/audio/audio_meet_priya_from_mumbai_her_dosa_is_cut_into_6_equal_pieces_she_eats_3_pieces_tha_17.mp3",
  "\"Is 3 by 6 the same as 1 by 2?\"": "/assets/audio/audio_is_3_by_6_the_same_as_1_by_2_18.mp3",
  "Let's check on the number line!": "/assets/audio/audio_let_s_check_on_the_number_line_19.mp3",
  "1 by 2, 2 by 4 and 3 by 6 all land on the SAME point on the number line! They are all equivalent — same value, different names!": "/assets/audio/audio_1_by_2_2_by_4_and_3_by_6_all_land_on_the_same_point_on_the_number_line_they_are__20.mp3",
  "\"1 by 2 equals 2 by 4 equals 3 by 6 — all equivalent!\"": "/assets/audio/audio_1_by_2_equals_2_by_4_equals_3_by_6_all_equivalent_21.mp3",
  "Same spot, different names!": "/assets/audio/audio_same_spot_different_names_22.mp3",
  "Multiply or divide the top AND bottom by the same number and you get an equivalent fraction. The value stays the same!": "/assets/audio/audio_multiply_or_divide_the_top_and_bottom_by_the_same_number_and_you_get_an_equivale_23.mp3",
  "\"1 by 2 times 2 by 2 equals 2 by 4 — multiply both parts equally!\"": "/assets/audio/audio_1_by_2_times_2_by_2_equals_2_by_4_multiply_both_parts_equally_24.mp3",
  "Now you know the secret!": "/assets/audio/audio_now_you_know_the_secret_25.mp3",
  "Make a bar that shows the same amount as the target fraction. Click segments to shade them!": "/assets/audio/audio_make_a_bar_that_shows_the_same_amount_as_the_target_fraction_click_segments_to_s_26.mp3",
  "Great! You shaded the matching fraction parts!": "/assets/audio/audio_great_you_shaded_the_matching_fraction_parts_27.mp3",
  "Super job! Both fractions cover the exact same area!": "/assets/audio/audio_super_job_both_fractions_cover_the_exact_same_area_28.mp3",
  "Awesome! You mastered the Fraction Bar Splitter station!": "/assets/audio/audio_awesome_you_mastered_the_fraction_bar_splitter_station_29.mp3",
  "Not quite! Try adjusting the parts to match the area.": "/assets/audio/audio_not_quite_try_adjusting_the_parts_to_match_the_area_30.mp3",
  "Click only the stepping stones with fractions equivalent to the starting fraction to cross safely to the treasure!": "/assets/audio/audio_click_only_the_stepping_stones_with_fractions_equivalent_to_the_starting_fractio_31.mp3",
  "Brilliant crossing! You found all the equivalent fraction stepping stones!": "/assets/audio/audio_brilliant_crossing_you_found_all_the_equivalent_fraction_stepping_stones_32.mp3",
  "Treasure unlocked! You crossed the fraction bridge like a champion!": "/assets/audio/audio_treasure_unlocked_you_crossed_the_fraction_bridge_like_a_champion_33.mp3",
  "That fraction is not equivalent. Choose carefully!": "/assets/audio/audio_that_fraction_is_not_equivalent_choose_carefully_34.mp3",
  "Press each magic multiplier button to see how multiplying top and bottom numbers creates equivalent fractions!": "/assets/audio/audio_press_each_magic_multiplier_button_to_see_how_multiplying_top_and_bottom_numbers_35.mp3",
  "Multiplied by 2! 2 by 3 transforms into 4 by 6!": "/assets/audio/audio_multiplied_by_2_2_by_3_transforms_into_4_by_6_36.mp3",
  "Multiplied by 3! 2 by 3 transforms into 6 by 9!": "/assets/audio/audio_multiplied_by_3_2_by_3_transforms_into_6_by_9_37.mp3",
  "Multiplied by 4! 2 by 3 transforms into 8 by 12!": "/assets/audio/audio_multiplied_by_4_2_by_3_transforms_into_8_by_12_38.mp3",
  "Multiplied by 5! 2 by 3 transforms into 10 by 15!": "/assets/audio/audio_multiplied_by_5_2_by_3_transforms_into_10_by_15_39.mp3",
  "Magical! You discovered all 4 equivalent fractions! Multiplying top and bottom by the same number keeps the value equal!": "/assets/audio/audio_magical_you_discovered_all_4_equivalent_fractions_multiplying_top_and_bottom_by__40.mp3",
  "Welcome to the Practice Phase! Travel around the world and solve equivalent fraction challenges to earn stars and XP!": "/assets/audio/audio_welcome_to_the_practice_phase_travel_around_the_world_and_solve_equivalent_fract_41.mp3",
  "Welcome to Toronto Bakery! Decide if the two fractions shown are equivalent.": "/assets/audio/audio_welcome_to_toronto_bakery_decide_if_the_two_fractions_shown_are_equivalent_42.mp3",
  "Welcome to Mumbai Market! Choose the fraction equivalent to the target.": "/assets/audio/audio_welcome_to_mumbai_market_choose_the_fraction_equivalent_to_the_target_43.mp3",
  "Welcome to Tokyo Sushi Bar! Find the missing number to make the fractions equivalent.": "/assets/audio/audio_welcome_to_tokyo_sushi_bar_find_the_missing_number_to_make_the_fractions_equival_44.mp3",
  "Correct!": "/assets/audio/audio_correct_45.mp3",
  "Great job!": "/assets/audio/audio_great_job_46.mp3",
  "Spot on!": "/assets/audio/audio_spot_on_47.mp3",
  "Well done!": "/assets/audio/audio_well_done_48.mp3",
  "Oops, not quite! Keep trying!": "/assets/audio/audio_oops_not_quite_keep_trying_49.mp3",
  "Fantastic work! You completed this world and earned your stars!": "/assets/audio/audio_fantastic_work_you_completed_this_world_and_earned_your_stars_50.mp3",
  "Incredible! You completed all the practice worlds around the world!": "/assets/audio/audio_incredible_you_completed_all_the_practice_worlds_around_the_world_51.mp3",
  "Good try! Replay this world to score enough stars to unlock the next destination!": "/assets/audio/audio_good_try_replay_this_world_to_score_enough_stars_to_unlock_the_next_destination_52.mp3",
  "Correct.": "/assets/audio/audio_correct_53.mp3",
  "Wrong.": "/assets/audio/audio_wrong_54.mp3"
};
