export const audioMap = {
  "Hmm... are these equal?": "/assets/audio/audio_hmm_are_these_equal_0.mp3",
  "John has 1 by 2 of a pizza. Sarah has 2 by 4 of the SAME size pizza. Who has more?": "/assets/audio/audio_john_has_1_by_2_of_a_pizza_sarah_has_2_by_4_of_the_same_size_pizza_who_has_more_1.mp3",
  "When two fractions cover the same area, they are called equivalent fractions!": "/assets/audio/audio_when_two_fractions_cover_the_same_area_they_are_called_equivalent_fractions_2.mp3",
  "Mei has a chocolate bar cut into 4 pieces and eats 2. John's bar is cut into 2 — he eats 1. Did they eat the same amount?": "/assets/audio/audio_mei_has_a_chocolate_bar_cut_into_4_pieces_and_eats_2_john_s_bar_is_cut_into_2_he_3.mp3",
  "Two fractions that look different can still be equal!": "/assets/audio/audio_two_fractions_that_look_different_can_still_be_equal_4.mp3",
  "Priya's dosa is cut into 6 pieces. She eats 3. Is that the same as eating 1 by 2?": "/assets/audio/audio_priya_s_dosa_is_cut_into_6_pieces_she_eats_3_is_that_the_same_as_eating_1_by_2_5.mp3",
  "3 by 6 and 1 by 2... are they secretly the same fraction?": "/assets/audio/audio_3_by_6_and_1_by_2_are_they_secretly_the_same_fraction_6.mp3",
  "Meet John from Toronto. He has a chocolate bar cut into 2 equal pieces. He eats 1 piece. That's one half!": "/assets/audio/audio_meet_john_from_toronto_he_has_a_chocolate_bar_cut_into_2_equal_pieces_he_eats_1__7.mp3",
  "\"John eats 1 by 2 of his chocolate bar!\"": "/assets/audio/audio_john_eats_1_by_2_of_his_chocolate_bar_8.mp3",
  "One out of two equal parts!": "/assets/audio/audio_one_out_of_two_equal_parts_9.mp3",
  "Meet Mei from Beijing. She has the SAME size chocolate bar, cut into 4 equal pieces. She eats 2 pieces. That's two quarters!": "/assets/audio/audio_meet_mei_from_beijing_she_has_the_same_size_chocolate_bar_cut_into_4_equal_piece_10.mp3",
  "\"Mei eats 2 by 4 of her bar!\"": "/assets/audio/audio_mei_eats_2_by_4_of_her_bar_11.mp3",
  "Two out of four equal parts!": "/assets/audio/audio_two_out_of_four_equal_parts_12.mp3",
  "Look — the shaded part is exactly equal! John's 1 by 2 and Mei's 2 by 4 cover the same area. They are EQUIVALENT fractions!": "/assets/audio/audio_look_the_shaded_part_is_exactly_equal_john_s_1_by_2_and_mei_s_2_by_4_cover_the_s_13.mp3",
  "\"1 by 2 equals 2 by 4 — same value, different names!\"": "/assets/audio/audio_1_by_2_equals_2_by_4_same_value_different_names_14.mp3",
  "Equivalent means equal value!": "/assets/audio/audio_equivalent_means_equal_value_15.mp3",
  "Meet Priya from Mumbai. Her dosa is cut into 6 equal pieces. She eats 3 pieces — that's 3 by 6. Is it the same as 1 by 2?": "/assets/audio/audio_meet_priya_from_mumbai_her_dosa_is_cut_into_6_equal_pieces_she_eats_3_pieces_tha_16.mp3",
  "\"Is 3 by 6 the same as 1 by 2?\"": "/assets/audio/audio_is_3_by_6_the_same_as_1_by_2_17.mp3",
  "Let's check on the number line!": "/assets/audio/audio_let_s_check_on_the_number_line_18.mp3",
  "1 by 2, 2 by 4 and 3 by 6 all land on the SAME point on the number line! They are all equivalent — same value, different names!": "/assets/audio/audio_1_by_2_2_by_4_and_3_by_6_all_land_on_the_same_point_on_the_number_line_they_are__19.mp3",
  "\"1 by 2 equals 2 by 4 equals 3 by 6 — all equivalent!\"": "/assets/audio/audio_1_by_2_equals_2_by_4_equals_3_by_6_all_equivalent_20.mp3",
  "Same spot, different names!": "/assets/audio/audio_same_spot_different_names_21.mp3",
  "Multiply or divide the top AND bottom by the same number and you get an equivalent fraction. The value stays the same!": "/assets/audio/audio_multiply_or_divide_the_top_and_bottom_by_the_same_number_and_you_get_an_equivale_22.mp3",
  "\"1 by 2 times 2 by 2 equals 2 by 4 — multiply both parts equally!\"": "/assets/audio/audio_1_by_2_times_2_by_2_equals_2_by_4_multiply_both_parts_equally_23.mp3",
  "Now you know the secret!": "/assets/audio/audio_now_you_know_the_secret_24.mp3",
  "Correct.": "/assets/audio/audio_correct_25.mp3",
  "Wrong.": "/assets/audio/audio_wrong_26.mp3"
};
